### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [valeoai/xmuda#1]
It's very interesting. How long does the model need to train?

**Comment by maxjaritz** [comment]
Training 2D and 3D at the same time (standard setup), the training times are approx. as follows for the A2D2/Sem.KITTI scenario:
baseline 30h
xMUDA 50h
xMUDA_PL 50h

For the NuScenes splits, the training time is faster (~26h for baseline and ~36h for xMUDA/xMUDA_PL)

Note that training can vary a lot depending on available CPU (SparseConvNet uses a lot of CPU resources).

Hope it helps.
