### ISSUE TITLE
nuScenes dataset

### ISSUE THREAD

**Issue by torchlidar** [valeoai/xmuda#11]
Hello, Thank you for your attractive paper and code.

I have a question about the dataset.
Is it only the metadata of the nuScenes dataset, or should I get all 10 ASIAs and USAs of this type?

![image](https://user-images.githubusercontent.com/65699167/93731774-73725780-fc09-11ea-81af-366a07e0e9b5.png)

**Comment by maxjaritz** [comment]
You need to download all data. US, Asia are different server options. You can either download from the Asia or from the US server.
