### ISSUE TITLE
Pseudo label generation part

### ISSUE THREAD

**Issue by torchlidar** [valeoai/xmuda#12]
Hi, Thank you for the nice code!

I have a question about the Pseudo label generation part
I did `python xmuda/test.py --cfg=configs/a2d2_semantic_kitti/xmuda.yaml --pselab @/model_2d_100000.pth @/model_3d_100000.pth DATASET_TARGET.TEST "('train',)" VAL.BATCH_SIZE 1`

But, I got an empty train.npy .....
Is there no Pseudo label generation part in this code?
So is there any way I can do it?

I'll wait for your answer. Thank you.

**Comment by maxjaritz** [comment]
Can you put a breakpoint here and check that you indeed append data during the `test.py` execution:
https://github.com/valeoai/xmuda/blob/8b39f8f77f048cd4c086323dd89fbf9710335d35/xmuda/data/utils/validate.py#L79
