### ISSUE TITLE
different lidar points density between a2d2 and semantickitti

### ISSUE THREAD

**Issue by huixiancheng** [valeoai/xmuda#14]
Hi,thx for the open source code.however ,when I preprocess the A2D2 and SemanticKITTI and loader them.I find the lidar point density between two dataset is very different.
just look like this
a2d2
![1](https://user-images.githubusercontent.com/65054204/100568412-1defb080-3306-11eb-8511-87d654c8aa3a.png)
semkitti
![2](https://user-images.githubusercontent.com/65054204/100568416-1fb97400-3306-11eb-8938-026066d1e23f.png)
so,is it cause by the dataset itself?or is influence by the way to process them?

**Comment by maxjaritz** [comment]
Hi, that is normal, because the datasets use different sensors. This is indeed a challenge for domain adaptation which is why it is an interesting domain adaptation scenario.

**Comment by huixiancheng** [comment]
All right!，thanks for your reply
