### ISSUE TITLE
Info about 3D segmentation module

### ISSUE THREAD

**Issue by saltoricristiano** [valeoai/xmuda#15]
Thank you for the very interesting work! 
Just a quick question about the 3D segmentation part. Have you tried to run only the 3D segmentation part alone in the baseline setup? If yes, how does it perform on each datasets?
Cheers!

**Comment by maxjaritz** [comment]
Yes, we report the `baseline (source only)' in the paper. It was trained on the source dataset only without any domain adaptation.

Best,
Max
