### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Eaton2022** [valeoai/xmuda#19]
cuda version:10.0
torch version:1.4.0
print(torch.cuda.is_available())
>>false
I wonder how can I solve this problem?

**Comment by Eaton2022** [comment]
solved  pip install https://download.pytorch.org/whl/cu100/torch-1.4.0%2Bcu100-cp38-cp38-linux_x86_64.whl

**Comment by shahriar0651** [comment]
Did torch 1.4 work with the existing `SparseConvNet` model for you?
