### ISSUE TITLE
error about preprocessing

### ISSUE THREAD

**Issue by AmingWu** [valeoai/xmuda#2]
When I run the semantic_kitti/preprocess.py, there is an error.

calib_out['Tr'][:3, :4] = calib_all['Tr'].reshape(3, 4) (line 71).

KeyError: 'Tr'.

When I print calib_all.keys(), the output is dict_keys(['P0', 'P1', 'P2', 'P3']).

**Comment by maxjaritz** [comment]
Please download the data_odometry_calib.zip and extract it.

Explanation: Even though extracting data_odometry_color.zip generates calib.txt files in each sequence folder, they do not contain the Tr matrix.
