### ISSUE TITLE
The coordinates are not on GPU

### ISSUE THREAD

**Issue by chester256** [valeoai/xmuda#4]
https://github.com/valeoai/xmuda/blob/8b39f8f77f048cd4c086323dd89fbf9710335d35/xmuda/train_xmuda.py#L172

It seems that only features of data_batch are copied to GPU. Does this slow down computation? Thanks.

**Comment by maxjaritz** [comment]
I followed the SparseConvNet implementation:
https://github.com/facebookresearch/SparseConvNet/blob/master/examples/ScanNet/unet.py

They do not copy the coordinates onto the GPU. I just did a quick test and it seems slightly faster to keep the coordinates on the CPU. This seems logical as the indexing using hash table in SparseConvNet is done with the CPU.

**Comment by chester256** [comment]
I see. Thanks!
