### ISSUE TITLE
The "PL" experiment

### ISSUE THREAD

**Issue by chester256** [valeoai/xmuda#6]
The paper says:

> Regarding PL, we apply [17] as follows: we generate pseudo-labels offline with a first training without UDA, and discard unconfident labels through class-wise thresholding. Then, we run a second training from scratch adding PL loss on target. The image-2-image translation part was excluded due to its instability, high training complexity and incompatibility with LiDAR data, thus limiting reproducibility.

So for [17], the domain adversarial training part is also excluded? Is the pseudo-label part the only kept part? Thanks

**Comment by maxjaritz** [comment]
Yes, that's right. We also exclude the domain adversarial part.

**Comment by chester256** [comment]
Have you ever tried domain adversarial training? I have tried [AdaptSegNet](https://github.com/wasidennis/AdaptSegNet), but it seems that it will bring negative transfer.

**Comment by maxjaritz** [comment]
Sorry for the late reply. No, we have not tried domain adversarial training. It would be interesting, but would need to be carried out separately for 2D and 3D. For 3D, there is very few work on this. PointDAN (https://arxiv.org/abs/1911.02744) does only classification, not segmentation.

**Comment by maxjaritz** [comment]
I am closing this as the question seems to be answered.
